### ISSUE TITLE
关于PHP8版本的PDOException: There is no active transaction问题

### ISSUE THREAD

**Issue by EricLiuCN** [Abbotton/saas-skeleton#3]
首先感谢作者分享这么棒的项目，我现在遇到一个PHP8版本的问题不知如何解决。

在PHP7版本，项目可以跑起来没有一点问题，但是我升级到PHP8.1版本之后添加租户会报PDOException: There is no active transaction的错误，但租户和数据库都能创建成功。
我搜索了这个问题之后，发现是一个关于DB的隐式提交的玩意。[Implicit Commits](https://laravel.com/docs/8.x/database#implicit-commits-in-transactions)
archtechx/tenancy这个扩展包的issues也提到了这个问题，https://github.com/archtechx/tenancy/issues/720

我按照说明在TenantServiceProvider.php 文件的Events\TenantCreated创建时，把shouldBeQueued(false) 改成 shouldBeQueued(true)并没有解决问题。现在不知道怎么处理了，难道我只能在PHP7版本跑这个项目吗？

期待您有此问题的解决办法，感谢！！！

**Comment by Abbotton** [comment]
这一两天我抽时间看一下, 抱歉.

**Comment by EricLiuCN** [comment]
这个问题使用redis队列可以解决。之前不成功是我队列的问题 ，操作方法：https://github.com/archtechx/tenancy/issues/720#issuecomment-925914089

再次感谢作者的分享。

**Comment by gaoheming** [comment]
> 这个问题使用redis队列可以解决。之前不成功是我队列的问题 ，操作方法：[archtechx/tenancy#720 (comment)](https://github.com/archtechx/tenancy/issues/720#issuecomment-925914089)
> 
> 再次感谢作者的分享。

队列的配置方法，能否分享下，一直没有配成功！！

**Comment by iYting** [comment]
> 这个问题使用redis队列可以解决。之前不成功是我队列的问题 ，操作方法：[archtechx/tenancy#720 (comment)](https://github.com/archtechx/tenancy/issues/720#issuecomment-925914089)
> 
> 再次感谢作者的分享。
你好 ， 我也遇到你说的这个问题，我已经把shouldBeQueued设置为true，但是问题已经存在，你说的【使用redis队列可以解决】具体怎么操作？
![image](https://github.com/user-attachments/assets/2fda75ea-b405-4fc6-9651-98eed3f700bf)

**Comment by EricLiuCN** [comment]
这个问题是很久之前遇到的了，laravel的.env文件中的QUEUE_CONNECTION设置为redis，默认的sync应该是不行的。把队列正确跑起来就可以，没有其他的操作。
